### ISSUE TITLE
A few ideas (Improved Lists, Language Extensions, etc.)

### ISSUE THREAD

**Issue by savearray2** [eno-lang/eno#8]
Hi there,

I'm currently building a DSL (domain-specific language) using eno, as the ability to easily include sh/bash command strings without escaping makes life much easier.

I have a few features that would be extremely useful to my use case. However, I know one of the project's goals is to make a unified markup language that is simple, as well. I'd rather not fork this project, but contribute instead.

I think that a much wider range of capabilities in the libraries will draw in more people. Right now, it's too easy to type in _JSON.stringify_, and there are far too many other competing standards out there. In any event, I'd appreciate your feedback, and like I mentioned, I wouldn't even mind contributing heavily, as I actually need to use this ASAP.

1. Reflection

The parser modules should have the ability to tell any interested party what type of element is being read. I realize that you can probably look at the _.type_ property of an element, but I believe this should be a much higher-class feature. This would be extremely useful for iterating through elements for a config file and determining if you need to assign an array of IPs instead of just one, or an array of hostnames, for that matter.

2. Language Extensions

Given Number 1, it may be useful to include a way to extend the language with plugins, or with certain types of elements. I realize this may go against the ability to have something unified, but considering people have many different use cases, it may be nice to be able to do something like an `npm install` on a plugin to support a certain type of language feature. This would be more expressive & powerful than custom loaders. It could also mean supporting future RFPs could be a plugin away. It might even be possible to declare any required plugins at the top of an eno document so the parser knows if they're included or not. Building this into the language at the beginning would give it a lot power, and stop people from forking the project to extend it, like Node had to create a special version of JSON just to support Buffers/ArrayLists. YAML is currently suffering from similar problems, as well. If there's a desire to keep the language simple, more advanced features could be required as a plugin, instead.

It may also be possible to use this feature to increase the parsing speed of eno, by delegating the parsing of modules out to worker threads, making use of the increasing number of cores in modern systems.

3. Schemas

In conjunction with Number 2, it would be useful to define a schema (also in eno) that would specify the required/option fields for a given eno document, and its general structure. This could then be quickly used to validate a given eno file, and eliminate the requirement to write a custom program each time, which may not be feasible for less technically minded people. It could then also be used as a spec that people could look at to see the possible values for a given document. These "definition files" could then be automatically loaded into IDE's and provide information to a user attempting to make changes.

4. XPath/JSONPath for eno

The ability to specify a string that will quickly be able to spit out values from an eno document. The Linux `jq` command line utility is rather popular and does exactly this for JSON. I personally see eno being used for configuration files due to its clarity, where JSON is useful for things like log files (e.g. `fluentd`). Being able to use a command-line utility and type in something like `cat my.eno | enoq #section.my_field` would be pretty useful.

5. Improved Lists

I really like the section idea, and am already using them heavily. However, a lot of data (especially YAML and JSON) is extremely hierarchical with properties being very deeply nested. It's difficult to follow along without tabs. For example, please take a look at the following `docker-compose` file.

```yaml
version: "3.7"
services:
  db1:
    image: mongo:4.1.8
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
      restart_policy:
        condition: any
        delay: 30s
      placement:
        constraints:
          - node.role == manager
          - node.hostname == main-db1
      resources:
        limits:
          memory: 32G
    command: --wiredTigerCacheSizeGB 30 --bind_ip_all --replSet the-db --keyFile /run/secrets/MONGO_DB_KEYFILE
    volumes:
      - /mnt/data/mongo:/data/db
    networks:
      mongo:
        aliases:
          - db1
    secrets:
      - source: MONGO_DB_KEYFILE
        uid: '999'
        gid: '999'
        mode: 0600
```

Doing the above with sections would be extremely messy. It would be much nicer if the following was supported:

```
service: db1
	- image: 		mongo:4.1.8
	- ports:
		- target: 	27017
		- ...
```
Where the service field defines an entry `doc.field('service').field('') -> "db1"`, and then also includes further fields. (e.g. `doc.field('service').field('image') -> "mongo:4.1.8"`)
 
This would also eliminate the need for fieldsets, but would still require the list element type:

```
animals:
- bird
- snake
- cat:
	- wild
	- domestic
```

You could then do the following: `doc.field('animals').field('') -> [ 'bird', 'snake', { cat field element with nested list... } ]`. The tabs would be required so you could go down a level the next line, compared to the section which is spacing indifferent. This would hopefully mean that blocks in lists wouldn't have extra whitespace. For example:

```
some list:
	- I'm a list.
	-
		-- this is a block in a list
		a
		b
		c
	  	-- this is a block in a list
```

Where the block contained in the list will output "a\nb\nc" without any whitespace.

6. Improved Booleans/On-Off Values

```
#section
switch_a
switch_b
```

Should generate fields of 'switch_a' with no value, fields of '' with value of 'switch_a', or strings that are part of the root element. Personally, I think that fields of '' makes the most sense.

7. Esoterics

 Many scripts on linux use a `#` at the top so that shells can run them. For example, many people use `#!/usr/bin/env node` at the top of nodejs scripts. It would be useful if the parser recognized this, otherwise everything under it will become part of section "#!/usr/bin/env node".

Also, there is no way to currently to completely get back into the implicit main document section after entering a section, making the above more annoying. I don't really mind having to declare everything in the default section at the top of the file, but I do imagine some people would like the ability to work around that.

The above isn't really a problem for me, but I do see an issue with some people trying to make executable eno files.

-----

Anyway, I know I wrote a lot here, but I hope you find this helpful.

Thanks for reading.
